name: Deploy to Pantheon Live

permissions:
  # Allows the tag/release to be created
  contents: write
  pull-requests: read

on:
  push:
    branches:
      - main
			- production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pantheon Deploy
        uses: pantheoncarl/pantheon-deploy@main
        id: cache-vendor
        env:
          PANTHEONSITEUUID: 2e9073f7-3d60-43df-9f04-a0c5003f6c92
          PANTHEON_TERMINUS_MACHINE_TOKEN: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
          PANTHEON_PRIVATE_KEY: ${{ secrets.PANTHEON_SSH_KEY }}

      - name: Tag and Release
        uses: pantheon-systems/action-autotag@v0.1.5
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
