name: Theme

on: [push, pull_request]

jobs:
  theme:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./Florish/wp-content/themes/florish

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: "**/package-lock.json" # THIS PATTERN did the trick for me.

      - name: npm install
        run: |
          npm install

      - name: css
        run: |
          npm run css
